
version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sq
    ports:
      - "5432:5432"
    restart: unless-stopped

  amigoscode-api:
    container_name: amigos-backend
    image: amigos-backend
    build:
      context: backend
      dockerfile: Dockerfile
      args:
       APP_NAME: amigos-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fullstack
    ports:
      - "8088:8088"
    depends_on:
      - db
    restart: unless-stopped

  amigoscode-react:
    container_name: amigoscode-react
    image: amigoscode-react
    build:
      context: frontend/react
      dockerfile: Dockerfile
      args:
        api_base_url: http://localhost:8088
        APP_NAME: amigoscode-react
    ports:
      - "5173:5173"
    depends_on:
      -  amigoscode-api
    restart: unless-stopped

volumes:
  db: