server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fullstack
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
