GET http://localhost:8088/api/v1/customers
Authorization: Bearer 1eyJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsiUk9MRV9VU0VSIl0sInN1YiI6InNsYXZhM0BnbWFpbC5jb20iLCJpc3MiOiJodHRwczovL2FtaWdvc2NvZGUuY29tIiwiaWF0IjoxNjgzODY5NDQwLCJleHAiOjE2ODUxNjU0NDB9.8BafVMxuAJxg6CUpZAm5Jp5OXul3l4ChhHSI3A53LqM
