GET http://localhost:8080/api/v1/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsiUk9MRV9VU0VSIl0sInN1YiI6InRlc3QiLCJpc3MiOiJodHRwczovL2FtaWdvc2NvZGUuY29tIiwiaWF0IjoxNjg1MTA1MzY5LCJleHAiOjE2ODY0MDEzNjl9.j1lxRT8QMW9QsbnVewjZoyjRf5Royh_yvkl2aXsMaJ4"

