GET http://localhost:9988/api/v1/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzY29wZXMiOlsiUk9MRV9VU0VSIl0sInN1YiI6InRlc3QiLCJpc3MiOiJodHRwczovL2FtaWdvc2NvZGUuY29tIiwiaWF0IjoxNjg1MTAyNDEwLCJleHAiOjE2ODYzOTg0MTB9.ZngtyFrNcVrG9sAAUPHJx4k0i6lS0LH5mSXNbuj-jjU
