GET http://localhost:8080/api/v1/customers/1

###
GET localhost:8080/api/v1/customers

###
GET http://localhost:8080/api/v1/customers/3

###
POST localhost:8080/api/v1/customers
Content-Type: application/json

{
  "name": "Joe",
  "email": "joe11@gmail.com",
  "age": 52
}

###
DELETE http://localhost:8080/api/v1/customers/1

###
GET localhost:8080/api/v1/customers

###
PUT localhost:8080/api/v1/customers/1
Content-Type: application/json

{
  "age": 75
}
