server:
  port: 9988
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  datasource:
#    url: jdbc:postgresql://127.0.0.1:5332/fullstack
    url: jdbc:postgresql://localhost:5432/fullstack
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
